image:
  repository: cicddevops.azurecr.io/api-test-develop
  tag: "v1"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 443

serviceAccount:
  create: true
  name: ""

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80